
service: basalt-assessment
frameworkVersion: '2 || 3'
useDotenv: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: '20201221'

package:
  exclude:
    - venv/**
    - src/react-app/**
    - src/express-server/**
    - readme.md
    - .prettierrc
    - .npmrc
    - .gitignore
  excludeDevDependencies: true

functions:
  app:
    handler: ./dist-server/server.handler
    events:
      - httpApi: '*'