
service: basalt-assessment
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.cjs
    includeModules: true
  serverless-offline:
    noPrependStageInUrl: true


provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    DB_PASSWORD: 'zSOFTZf7e4bE4506'
    DB_USER: 'callanblythebrom'
    DB_NAME: 'test'
    API_VERSION: '1'
    NODE_ENV: 'Development'
    URL: "http://localhost"
    PORT: "8000"

package:
  individually: true
  exclude: node_modules

functions:
  app:
    handler: src/express-server/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
